name: Release Image

on:
  # Workflow runs when a release is created in GitHub
  release:
    types: [published]

env:
  IMAGE_REG: ghcr.io
  IMAGE_REPO: sra1kumar30/postman-prometheus

permissions:
  packages: write

jobs:
  release:
    name: Release image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Build image tagged with release tag name, should be a semver
      - name: Build the container image
        run: make image IMAGE_TAG=${{ github.event.release.tag_name }}

      # Then push image to registry
      - name: Push to container registry
        if: ${{ !env.ACT }}
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login $IMAGE_REG -u $GITHUB_ACTOR --password-stdin
          make push IMAGE_TAG=${{ github.event.release.tag_name }}
